/*
 * gmodstore
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Everyday.GmodStore.Sdk.Client.OpenAPIDateConverter;

namespace Everyday.GmodStore.Sdk.Model
{
    /// <summary>
    /// ProductPrice
    /// </summary>
    [DataContract(Name = "ProductPrice")]
    public partial class ProductPrice : IEquatable<ProductPrice>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductPrice" /> class.
        /// </summary>
        /// <param name="raw">Value of the money in smallest denomination of &#x60;currency&#x60; (e.g cents for USD).</param>
        /// <param name="original">original.</param>
        /// <param name="purchase">purchase.</param>
        public ProductPrice(int raw = default(int), Money original = default(Money), Money purchase = default(Money))
        {
            this.Raw = raw;
            this.Original = original;
            this.Purchase = purchase;
        }

        /// <summary>
        /// Value of the money in smallest denomination of &#x60;currency&#x60; (e.g cents for USD)
        /// </summary>
        /// <value>Value of the money in smallest denomination of &#x60;currency&#x60; (e.g cents for USD)</value>
        [DataMember(Name = "raw", EmitDefaultValue = false)]
        public int Raw { get; set; }

        /// <summary>
        /// Gets or Sets Original
        /// </summary>
        [DataMember(Name = "original", EmitDefaultValue = false)]
        public Money Original { get; set; }

        /// <summary>
        /// Gets or Sets Purchase
        /// </summary>
        [DataMember(Name = "purchase", EmitDefaultValue = false)]
        public Money Purchase { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductPrice {\n");
            sb.Append("  Raw: ").Append(Raw).Append("\n");
            sb.Append("  Original: ").Append(Original).Append("\n");
            sb.Append("  Purchase: ").Append(Purchase).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductPrice);
        }

        /// <summary>
        /// Returns true if ProductPrice instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductPrice to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductPrice input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Raw == input.Raw ||
                    this.Raw.Equals(input.Raw)
                ) && 
                (
                    this.Original == input.Original ||
                    (this.Original != null &&
                    this.Original.Equals(input.Original))
                ) && 
                (
                    this.Purchase == input.Purchase ||
                    (this.Purchase != null &&
                    this.Purchase.Equals(input.Purchase))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Raw.GetHashCode();
                if (this.Original != null)
                    hashCode = hashCode * 59 + this.Original.GetHashCode();
                if (this.Purchase != null)
                    hashCode = hashCode * 59 + this.Purchase.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
