/*
 * gmodstore
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Everyday.GmodStore.Sdk.Client;
using Everyday.GmodStore.Sdk.Model;

namespace Everyday.GmodStore.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPermissionGroupsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a permission group
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <returns>CreatePermissionGroupResponse</returns>
        CreatePermissionGroupResponse CreatePermissionGroup(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload));

        /// <summary>
        /// Create a permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <returns>ApiResponse of CreatePermissionGroupResponse</returns>
        ApiResponse<CreatePermissionGroupResponse> CreatePermissionGroupWithHttpInfo(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload));
        /// <summary>
        /// Delete the specified permission group
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>DeletePermissionGroupResponse</returns>
        DeletePermissionGroupResponse DeletePermissionGroup(string permissionGroup);

        /// <summary>
        /// Delete the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>ApiResponse of DeletePermissionGroupResponse</returns>
        ApiResponse<DeletePermissionGroupResponse> DeletePermissionGroupWithHttpInfo(string permissionGroup);
        /// <summary>
        /// Show the specified permission group
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>GetPermissionGroupResponse</returns>
        GetPermissionGroupResponse GetPermissionGroup(string permissionGroup);

        /// <summary>
        /// Show the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>ApiResponse of GetPermissionGroupResponse</returns>
        ApiResponse<GetPermissionGroupResponse> GetPermissionGroupWithHttpInfo(string permissionGroup);
        /// <summary>
        /// List all permission groups
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <returns>Object</returns>
        Object ListPermissionGroups(int? perPage = default(int?), string cursor = default(string));

        /// <summary>
        /// List all permission groups
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ListPermissionGroupsWithHttpInfo(int? perPage = default(int?), string cursor = default(string));
        /// <summary>
        /// Update the specified permission group
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <returns>UpdatePermissionGroupResponse</returns>
        UpdatePermissionGroupResponse UpdatePermissionGroup(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload));

        /// <summary>
        /// Update the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <returns>ApiResponse of UpdatePermissionGroupResponse</returns>
        ApiResponse<UpdatePermissionGroupResponse> UpdatePermissionGroupWithHttpInfo(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPermissionGroupsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreatePermissionGroupResponse</returns>
        System.Threading.Tasks.Task<CreatePermissionGroupResponse> CreatePermissionGroupAsync(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreatePermissionGroupResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreatePermissionGroupResponse>> CreatePermissionGroupWithHttpInfoAsync(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeletePermissionGroupResponse</returns>
        System.Threading.Tasks.Task<DeletePermissionGroupResponse> DeletePermissionGroupAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeletePermissionGroupResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeletePermissionGroupResponse>> DeletePermissionGroupWithHttpInfoAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Show the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPermissionGroupResponse</returns>
        System.Threading.Tasks.Task<GetPermissionGroupResponse> GetPermissionGroupAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Show the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPermissionGroupResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetPermissionGroupResponse>> GetPermissionGroupWithHttpInfoAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List all permission groups
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ListPermissionGroupsAsync(int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List all permission groups
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ListPermissionGroupsWithHttpInfoAsync(int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdatePermissionGroupResponse</returns>
        System.Threading.Tasks.Task<UpdatePermissionGroupResponse> UpdatePermissionGroupAsync(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update the specified permission group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdatePermissionGroupResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdatePermissionGroupResponse>> UpdatePermissionGroupWithHttpInfoAsync(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPermissionGroupsApi : IPermissionGroupsApiSync, IPermissionGroupsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PermissionGroupsApi : IPermissionGroupsApi
    {
        private Everyday.GmodStore.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionGroupsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PermissionGroupsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionGroupsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PermissionGroupsApi(string basePath)
        {
            this.Configuration = Everyday.GmodStore.Sdk.Client.Configuration.MergeConfigurations(
                Everyday.GmodStore.Sdk.Client.GlobalConfiguration.Instance,
                new Everyday.GmodStore.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Everyday.GmodStore.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Everyday.GmodStore.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Everyday.GmodStore.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionGroupsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PermissionGroupsApi(Everyday.GmodStore.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Everyday.GmodStore.Sdk.Client.Configuration.MergeConfigurations(
                Everyday.GmodStore.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Everyday.GmodStore.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Everyday.GmodStore.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Everyday.GmodStore.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionGroupsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public PermissionGroupsApi(Everyday.GmodStore.Sdk.Client.ISynchronousClient client, Everyday.GmodStore.Sdk.Client.IAsynchronousClient asyncClient, Everyday.GmodStore.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Everyday.GmodStore.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Everyday.GmodStore.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Everyday.GmodStore.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Everyday.GmodStore.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Everyday.GmodStore.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <returns>CreatePermissionGroupResponse</returns>
        public CreatePermissionGroupResponse CreatePermissionGroup(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<CreatePermissionGroupResponse> localVarResponse = CreatePermissionGroupWithHttpInfo(newPermissionGroupPayload);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <returns>ApiResponse of CreatePermissionGroupResponse</returns>
        public Everyday.GmodStore.Sdk.Client.ApiResponse<CreatePermissionGroupResponse> CreatePermissionGroupWithHttpInfo(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload))
        {
            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = newPermissionGroupPayload;

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreatePermissionGroupResponse>("/api/v3/permission-groups", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreatePermissionGroupResponse</returns>
        public async System.Threading.Tasks.Task<CreatePermissionGroupResponse> CreatePermissionGroupAsync(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<CreatePermissionGroupResponse> localVarResponse = await CreatePermissionGroupWithHttpInfoAsync(newPermissionGroupPayload, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="newPermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreatePermissionGroupResponse)</returns>
        public async System.Threading.Tasks.Task<Everyday.GmodStore.Sdk.Client.ApiResponse<CreatePermissionGroupResponse>> CreatePermissionGroupWithHttpInfoAsync(NewPermissionGroupPayload newPermissionGroupPayload = default(NewPermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = newPermissionGroupPayload;

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreatePermissionGroupResponse>("/api/v3/permission-groups", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>DeletePermissionGroupResponse</returns>
        public DeletePermissionGroupResponse DeletePermissionGroup(string permissionGroup)
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<DeletePermissionGroupResponse> localVarResponse = DeletePermissionGroupWithHttpInfo(permissionGroup);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>ApiResponse of DeletePermissionGroupResponse</returns>
        public Everyday.GmodStore.Sdk.Client.ApiResponse<DeletePermissionGroupResponse> DeletePermissionGroupWithHttpInfo(string permissionGroup)
        {
            // verify the required parameter 'permissionGroup' is set
            if (permissionGroup == null)
                throw new Everyday.GmodStore.Sdk.Client.ApiException(400, "Missing required parameter 'permissionGroup' when calling PermissionGroupsApi->DeletePermissionGroup");

            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("permission_group", Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToString(permissionGroup)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeletePermissionGroupResponse>("/api/v3/permission-groups/{permission_group}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeletePermissionGroupResponse</returns>
        public async System.Threading.Tasks.Task<DeletePermissionGroupResponse> DeletePermissionGroupAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<DeletePermissionGroupResponse> localVarResponse = await DeletePermissionGroupWithHttpInfoAsync(permissionGroup, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeletePermissionGroupResponse)</returns>
        public async System.Threading.Tasks.Task<Everyday.GmodStore.Sdk.Client.ApiResponse<DeletePermissionGroupResponse>> DeletePermissionGroupWithHttpInfoAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'permissionGroup' is set
            if (permissionGroup == null)
                throw new Everyday.GmodStore.Sdk.Client.ApiException(400, "Missing required parameter 'permissionGroup' when calling PermissionGroupsApi->DeletePermissionGroup");


            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("permission_group", Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToString(permissionGroup)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeletePermissionGroupResponse>("/api/v3/permission-groups/{permission_group}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Show the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>GetPermissionGroupResponse</returns>
        public GetPermissionGroupResponse GetPermissionGroup(string permissionGroup)
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<GetPermissionGroupResponse> localVarResponse = GetPermissionGroupWithHttpInfo(permissionGroup);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Show the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <returns>ApiResponse of GetPermissionGroupResponse</returns>
        public Everyday.GmodStore.Sdk.Client.ApiResponse<GetPermissionGroupResponse> GetPermissionGroupWithHttpInfo(string permissionGroup)
        {
            // verify the required parameter 'permissionGroup' is set
            if (permissionGroup == null)
                throw new Everyday.GmodStore.Sdk.Client.ApiException(400, "Missing required parameter 'permissionGroup' when calling PermissionGroupsApi->GetPermissionGroup");

            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("permission_group", Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToString(permissionGroup)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetPermissionGroupResponse>("/api/v3/permission-groups/{permission_group}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Show the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetPermissionGroupResponse</returns>
        public async System.Threading.Tasks.Task<GetPermissionGroupResponse> GetPermissionGroupAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<GetPermissionGroupResponse> localVarResponse = await GetPermissionGroupWithHttpInfoAsync(permissionGroup, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Show the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetPermissionGroupResponse)</returns>
        public async System.Threading.Tasks.Task<Everyday.GmodStore.Sdk.Client.ApiResponse<GetPermissionGroupResponse>> GetPermissionGroupWithHttpInfoAsync(string permissionGroup, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'permissionGroup' is set
            if (permissionGroup == null)
                throw new Everyday.GmodStore.Sdk.Client.ApiException(400, "Missing required parameter 'permissionGroup' when calling PermissionGroupsApi->GetPermissionGroup");


            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("permission_group", Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToString(permissionGroup)); // path parameter

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetPermissionGroupResponse>("/api/v3/permission-groups/{permission_group}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetPermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List all permission groups 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <returns>Object</returns>
        public Object ListPermissionGroups(int? perPage = default(int?), string cursor = default(string))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<Object> localVarResponse = ListPermissionGroupsWithHttpInfo(perPage, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List all permission groups 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public Everyday.GmodStore.Sdk.Client.ApiResponse<Object> ListPermissionGroupsWithHttpInfo(int? perPage = default(int?), string cursor = default(string))
        {
            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/api/v3/permission-groups", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPermissionGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List all permission groups 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ListPermissionGroupsAsync(int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<Object> localVarResponse = await ListPermissionGroupsWithHttpInfoAsync(perPage, cursor, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List all permission groups 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="perPage"> (optional, default to 24)</param>
        /// <param name="cursor">The cursor from which to return paginated results starting after (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Everyday.GmodStore.Sdk.Client.ApiResponse<Object>> ListPermissionGroupsWithHttpInfoAsync(int? perPage = default(int?), string cursor = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (perPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToMultiMap("", "perPage", perPage));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/api/v3/permission-groups", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPermissionGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <returns>UpdatePermissionGroupResponse</returns>
        public UpdatePermissionGroupResponse UpdatePermissionGroup(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<UpdatePermissionGroupResponse> localVarResponse = UpdatePermissionGroupWithHttpInfo(permissionGroup, updatePermissionGroupPayload);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <returns>ApiResponse of UpdatePermissionGroupResponse</returns>
        public Everyday.GmodStore.Sdk.Client.ApiResponse<UpdatePermissionGroupResponse> UpdatePermissionGroupWithHttpInfo(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload))
        {
            // verify the required parameter 'permissionGroup' is set
            if (permissionGroup == null)
                throw new Everyday.GmodStore.Sdk.Client.ApiException(400, "Missing required parameter 'permissionGroup' when calling PermissionGroupsApi->UpdatePermissionGroup");

            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("permission_group", Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToString(permissionGroup)); // path parameter
            localVarRequestOptions.Data = updatePermissionGroupPayload;

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<UpdatePermissionGroupResponse>("/api/v3/permission-groups/{permission_group}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdatePermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdatePermissionGroupResponse</returns>
        public async System.Threading.Tasks.Task<UpdatePermissionGroupResponse> UpdatePermissionGroupAsync(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Everyday.GmodStore.Sdk.Client.ApiResponse<UpdatePermissionGroupResponse> localVarResponse = await UpdatePermissionGroupWithHttpInfoAsync(permissionGroup, updatePermissionGroupPayload, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update the specified permission group 
        /// </summary>
        /// <exception cref="Everyday.GmodStore.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="permissionGroup"></param>
        /// <param name="updatePermissionGroupPayload"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdatePermissionGroupResponse)</returns>
        public async System.Threading.Tasks.Task<Everyday.GmodStore.Sdk.Client.ApiResponse<UpdatePermissionGroupResponse>> UpdatePermissionGroupWithHttpInfoAsync(string permissionGroup, UpdatePermissionGroupPayload updatePermissionGroupPayload = default(UpdatePermissionGroupPayload), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'permissionGroup' is set
            if (permissionGroup == null)
                throw new Everyday.GmodStore.Sdk.Client.ApiException(400, "Missing required parameter 'permissionGroup' when calling PermissionGroupsApi->UpdatePermissionGroup");


            Everyday.GmodStore.Sdk.Client.RequestOptions localVarRequestOptions = new Everyday.GmodStore.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Everyday.GmodStore.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("permission_group", Everyday.GmodStore.Sdk.Client.ClientUtils.ParameterToString(permissionGroup)); // path parameter
            localVarRequestOptions.Data = updatePermissionGroupPayload;

            // authentication (PersonalAccessToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<UpdatePermissionGroupResponse>("/api/v3/permission-groups/{permission_group}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdatePermissionGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
