/* 
 * GmodStore
 *
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Everyday.GmodStore.Sdk.Api;
using Everyday.GmodStore.Sdk.Model;
using Everyday.GmodStore.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Everyday.GmodStore.Sdk.Test
{
    /// <summary>
    ///  Class for testing AddonStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddonStatsTests
    {
        // TODO uncomment below to declare an instance variable for AddonStats
        //private AddonStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddonStats
            //instance = new AddonStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddonStats
        /// </summary>
        [Test]
        public void AddonStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddonStats
            //Assert.IsInstanceOfType<AddonStats> (instance, "variable 'instance' is a AddonStats");
        }


        /// <summary>
        /// Test the property 'Revenue'
        /// </summary>
        [Test]
        public void RevenueTest()
        {
            // TODO unit test for the property 'Revenue'
        }
        /// <summary>
        /// Test the property 'Views'
        /// </summary>
        [Test]
        public void ViewsTest()
        {
            // TODO unit test for the property 'Views'
        }
        /// <summary>
        /// Test the property 'Sales'
        /// </summary>
        [Test]
        public void SalesTest()
        {
            // TODO unit test for the property 'Sales'
        }

    }

}
