/*
 * GmodStore API
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Everyday.GmodStore.Sdk.Api;
using Everyday.GmodStore.Sdk.Model;
using Everyday.GmodStore.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Everyday.GmodStore.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AddonImages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddonImagesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddonImages
        //private AddonImages instance;

        public AddonImagesTests()
        {
            // TODO uncomment below to create an instance of AddonImages
            //instance = new AddonImages();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddonImages
        /// </summary>
        [Fact]
        public void AddonImagesInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddonImages
            //Assert.IsType<AddonImages>(instance);
        }


        /// <summary>
        /// Test the property 'Bigspot'
        /// </summary>
        [Fact]
        public void BigspotTest()
        {
            // TODO unit test for the property 'Bigspot'
        }
        /// <summary>
        /// Test the property 'Listing'
        /// </summary>
        [Fact]
        public void ListingTest()
        {
            // TODO unit test for the property 'Listing'
        }
        /// <summary>
        /// Test the property 'ListingSmall'
        /// </summary>
        [Fact]
        public void ListingSmallTest()
        {
            // TODO unit test for the property 'ListingSmall'
        }

    }

}
