/* 
 * GmodStore API
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Everyday.GmodStore.Sdk.Api;
using Everyday.GmodStore.Sdk.Model;
using Everyday.GmodStore.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Everyday.GmodStore.Sdk.Test
{
    /// <summary>
    ///  Class for testing AddonListResponse1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddonListResponse1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddonListResponse1
        //private AddonListResponse1 instance;

        public AddonListResponse1Tests()
        {
            // TODO uncomment below to create an instance of AddonListResponse1
            //instance = new AddonListResponse1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddonListResponse1
        /// </summary>
        [Fact]
        public void AddonListResponse1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddonListResponse1
            //Assert.IsInstanceOfType<AddonListResponse1> (instance, "variable 'instance' is a AddonListResponse1");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
