/*
 * GmodStore API
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Everyday.GmodStore.Sdk.Api;
using Everyday.GmodStore.Sdk.Model;
using Everyday.GmodStore.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Everyday.GmodStore.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AddonStatsViewsCurrent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddonStatsViewsCurrentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddonStatsViewsCurrent
        //private AddonStatsViewsCurrent instance;

        public AddonStatsViewsCurrentTests()
        {
            // TODO uncomment below to create an instance of AddonStatsViewsCurrent
            //instance = new AddonStatsViewsCurrent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddonStatsViewsCurrent
        /// </summary>
        [Fact]
        public void AddonStatsViewsCurrentInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddonStatsViewsCurrent
            //Assert.IsType<AddonStatsViewsCurrent>(instance);
        }


        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

    }

}
