/*
 * GmodStore API
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Everyday.GmodStore.Sdk.Client;
using Everyday.GmodStore.Sdk.Api;
// uncomment below to import models
//using Everyday.GmodStore.Sdk.Model;

namespace Everyday.GmodStore.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing AddonPurchasesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AddonPurchasesApiTests : IDisposable
    {
        private AddonPurchasesApi instance;

        public AddonPurchasesApiTests()
        {
            instance = new AddonPurchasesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddonPurchasesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AddonPurchasesApi
            //Assert.IsType<AddonPurchasesApi>(instance);
        }

        /// <summary>
        /// Test CreateAddonPurchase
        /// </summary>
        [Fact]
        public void CreateAddonPurchaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //NewAddonPurchase newAddonPurchase = null;
            //List<string> with = null;
            //var response = instance.CreateAddonPurchase(addonId, newAddonPurchase, with);
            //Assert.IsType<AddonPurchaseResponse>(response);
        }

        /// <summary>
        /// Test GetAddonPurchase
        /// </summary>
        [Fact]
        public void GetAddonPurchaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //long userId = null;
            //List<string> with = null;
            //var response = instance.GetAddonPurchase(addonId, userId, with);
            //Assert.IsType<AddonPurchaseResponse>(response);
        }

        /// <summary>
        /// Test ListAddonPurchases
        /// </summary>
        [Fact]
        public void ListAddonPurchasesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //List<string> with = null;
            //var response = instance.ListAddonPurchases(addonId, with);
            //Assert.IsType<AddonPurchaseListResponse>(response);
        }

        /// <summary>
        /// Test UpdateAddonPurchase
        /// </summary>
        [Fact]
        public void UpdateAddonPurchaseTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //long userId = null;
            //AddonPurchase addonPurchase = null;
            //List<string> with = null;
            //var response = instance.UpdateAddonPurchase(addonId, userId, addonPurchase, with);
            //Assert.IsType<AddonPurchaseResponse>(response);
        }
    }
}
