/*
 * GmodStore API
 *
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Everyday.GmodStore.Sdk.Client;
using Everyday.GmodStore.Sdk.Api;
// uncomment below to import models
//using Everyday.GmodStore.Sdk.Model;

namespace Everyday.GmodStore.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing AddonVersionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AddonVersionsApiTests : IDisposable
    {
        private AddonVersionsApi instance;

        public AddonVersionsApiTests()
        {
            instance = new AddonVersionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddonVersionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AddonVersionsApi
            //Assert.IsType<AddonVersionsApi>(instance);
        }

        /// <summary>
        /// Test CreateAddonVersion
        /// </summary>
        [Fact]
        public void CreateAddonVersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //NewAddonVersion newAddonVersion = null;
            //List<string> with = null;
            //var response = instance.CreateAddonVersion(addonId, newAddonVersion, with);
            //Assert.IsType<AddonVersionResponse>(response);
        }

        /// <summary>
        /// Test DownloadAddonVersion
        /// </summary>
        [Fact]
        public void DownloadAddonVersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //long versionId = null;
            //var response = instance.DownloadAddonVersion(addonId, versionId);
            //Assert.IsType<AddonDownloadResponse>(response);
        }

        /// <summary>
        /// Test GetAddonVersion
        /// </summary>
        [Fact]
        public void GetAddonVersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //long versionId = null;
            //List<string> with = null;
            //var response = instance.GetAddonVersion(addonId, versionId, with);
            //Assert.IsType<AddonVersionResponse>(response);
        }

        /// <summary>
        /// Test ListAddonVersions
        /// </summary>
        [Fact]
        public void ListAddonVersionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //List<string> with = null;
            //var response = instance.ListAddonVersions(addonId, with);
            //Assert.IsType<AddonVersionListResponse>(response);
        }

        /// <summary>
        /// Test UpdateAddonVersion
        /// </summary>
        [Fact]
        public void UpdateAddonVersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long addonId = null;
            //long versionId = null;
            //AddonVersion addonVersion = null;
            //List<string> with = null;
            //var response = instance.UpdateAddonVersion(addonId, versionId, addonVersion, with);
            //Assert.IsType<AddonVersionResponse>(response);
        }
    }
}
