/*
 * GmodStore
 *
 * Welcome to the GmodStore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace Everyday.GmodStore.Sdk.Client
{
/// <summary>
/// Http methods supported by swagger
/// </summary>
public enum HttpMethod
{
	/// <summary>HTTP GET request.</summary>
	Get,
	/// <summary>HTTP POST request.</summary>
	Post,
	/// <summary>HTTP PUT request.</summary>
	Put,
	/// <summary>HTTP DELETE request.</summary>
	Delete,
	/// <summary>HTTP HEAD request.</summary>
	Head,
	/// <summary>HTTP OPTIONS request.</summary>
	Options,
	/// <summary>HTTP PATCH request.</summary>
	Patch
}
}
