/* 
 * GmodStore
 *
 * Welcome to the Gmodstore API! You can use our API to access Gmodstore API endpoints, which can be used interact with Gmodstore programmatically.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NO.Everyday.GmodStoreSDK.Api;
using NO.Everyday.GmodStoreSDK.Model;
using NO.Everyday.GmodStoreSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NO.Everyday.GmodStoreSDK.Test
{
    /// <summary>
    ///  Class for testing AddonStatsViewsCurrent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddonStatsViewsCurrentTests
    {
        // TODO uncomment below to declare an instance variable for AddonStatsViewsCurrent
        //private AddonStatsViewsCurrent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddonStatsViewsCurrent
            //instance = new AddonStatsViewsCurrent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddonStatsViewsCurrent
        /// </summary>
        [Test]
        public void AddonStatsViewsCurrentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddonStatsViewsCurrent
            //Assert.IsInstanceOfType<AddonStatsViewsCurrent> (instance, "variable 'instance' is a AddonStatsViewsCurrent");
        }


        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Test]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

    }

}
